polls/urls.py
from django.urls import path

from . import views

app_name = 'polls' # Namespace para los paths, identifica las rutas de una aplicación especifica

urlpatterns = [
    # path('', views.index, name='index'), (1)
    # path('<int:id_pregunta>/', views.detail, name='detalle'), (1)
    # path('<int:id_pregunta>/resultados/', views.results, name='resultados'), (1)
    # path('<int:id_pregunta>/votar/', views.vote, name='votar') (1)
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detalle'),
    path('<int:pk>/resultados/', views.ResultsView.as_view(), name='resultados'),
    path('<int:id_pregunta>/votar/', views.vote, name='votar')
]

steezShoes_Back/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Importaciones para el API REST
from rest_framework import routers
from polls import views

router = routers.DefaultRouter()
router.register(r'usuarios', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('polls/', include('polls.urls')),
    path('steez/', include('shoes.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace = 'rest_framework'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class  Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=200)
    fecha_pub = models.DateTimeField('fecha publicacion') #Esto permite indicar un nombre leible por humanos para este campo

    def __str__(self):
        return self.texto_pregunta
    
    def fue_publicada_recientemente(self):
        ahora = timezone.now()
        return ahora >= self.fecha_pub >= ahora - datetime.timedelta(days=1)
    
    fue_publicada_recientemente.admin_order_field = 'fecha_pub'
    fue_publicada_recientemente.boolean = True
    fue_publicada_recientemente.short_description = '¿Publicada recientemente?'

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    texto_opcion = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_opcion

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Importaciones para el API REST
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, permissions
from .serializers import UserSerializer, GroupSerializer

# Modelos
from .models import Pregunta, Opcion

# def index(request):(1)
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'ultimas_preguntas'
    def get_queryset(self):
        # """ Retorna las ultimas cinco preguntas publicadas """ (4)
        # return  Pregunta.objects.order_by('-fecha_pub')[:5] (4)
        """ 
        Retorna las ultimas cinco preguntas publicadas (sin incluir aquellas
        que estan configuradas para ser publicadas en el futuro). 
        """
        return Pregunta.objects.filter(fecha_pub__lte = timezone.now()).order_by('-fecha_pub')[:5]
    # ultimas_preguntas = Pregunta.objects.order_by('-fecha_pub')[:5] (3)
    #response = ', '.join([p.texto_pregunta for p in ultimas_preguntas]) (1)
    #return HttpResponse(response) (1)
    #template = loader.get_template('polls/index.html') (2)
    # context = { (3)
    #     'ultimas_preguntas': ultimas_preguntas (3)
    # } (3)
    #return HttpResponse(template.render(context, request)) (2)
    # return render(request, 'polls/index.html', context) (3)

# def detail(request, id_pregunta): (1)
class DetailView(generic.DetailView):
    model = Pregunta
    template_name = 'polls/detail.html'
    # try:
    #     pregunta = Pregunta.objects.get(pk=id_pregunta) (1)
    # except Pregunta.DoesNotExist: (1)
    #     raise Http404("La pregunta no existe") (1)
    # return render(request, 'polls/detail.html', {'pregunta': pregunta}) (1)
    # pregunta = get_object_or_404(Pregunta, pk=id_pregunta) (2)
    # return render(request, 'polls/detail.html', {'pregunta': pregunta}) (2)

# def results(request, id_pregunta): (1)
class ResultsView(generic.DetailView):
    model = Pregunta
    template_name = 'polls/results.html'
    # response = "Estas mirando los resultados de la pregunta %s." (1)
    # return HttpResponse(response % id_pregunta) (1) 
    # pregunta = get_object_or_404(Pregunta, pk=id_pregunta) (2)
    # return render(request, 'polls/results.html',{ 'pregunta': pregunta }) (2)

def vote(request, id_pregunta):
    pregunta = get_object_or_404(Pregunta, pk=id_pregunta)
    try:
        opcion_elegida = pregunta.opcion_set.get(pk=request.POST['opcion'])
    except (KeyError, Opcion.DoesNotExist):
            # Volver a mostrar el formulario de votación
            return render(request, 'polls/detail.html', {
                'pregunta': pregunta,
                'mensaje_error': "No seleccionaste una opcion."
            })
    else:
        opcion_elegida.votos += 1
        opcion_elegida.save()
        # Siempre retornar un HttpResponseRedirect despues de tratar correctamente con una petición POST
        # Esto previene que los datos sean posteados dos veces si el usuario usa el botón "atras" del navegador
        return HttpResponseRedirect(reverse('polls:resultados', args=(pregunta.id,))) # La coma despues de 'pregunta.id' es fundamental, simpre incluirla para que args se procese como un iterable
    # return HttpResponse("Estas votando en la pregunta %s." % id_pregunta) (1)

class UserViewSet(viewsets.ModelViewSet):
    """
    API Endpoint que permite ver y editar usuarios
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]

class GroupViewSet(viewsets.ModelViewSet):
    """
    API Endpoint que permite ver y editar grupos
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle</title>
</head>
<body>
    <h1>{{ pregunta.texto_pregunta }}</h1>
    {% if mensaje_error %} <p><strong>{{ mensaje_error }}</strong></p>{% endif %}
    <form action="{% url 'polls:votar' pregunta.id %}" method="POST">
        {% csrf_token %}
        
        {% for opcion in pregunta.opcion_set.all %}
            <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id }}" >
            <label for="opcion{{ forloop.counter }}">{{ opcion.texto_opcion }}</label>
            <br>
        {% endfor %}
        <button type="submit">Votar</button>            
    </form>
    
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>

    {% if ultimas_preguntas %}
        <ul>
        {% for pregunta in ultimas_preguntas %}
            <li><a href="{% url 'polls:detalle' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hay encuestas disponibles.</p>
    {% endif %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados</title>
</head>
<body>
    <h1>{{ pregunta.texto_pregunta }}</h1>

    <ul>
        {% for opcion in pregunta.opcion_set.all %}
            <li>{{ opcion.texto_opcion }} -- {{ opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
        {% endfor %}
    </ul>
    
    <a href="{% url 'polls:detalle' pregunta.id %}">¿Volver a votar?</a>
    
</body>
</html>